### ISSUE TITLE
Can this work with TypeScript

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/snap-shot#72]
Would be great!

**Comment by wookieb** [comment]
You mean you need typing?

**Comment by janstrohbeck** [comment]
https://github.com/bahmutov/find-test-caller/pull/3

**Comment by ccorcos** [comment]
Agreed!

```
     TypeError: Cannot destructure property `specName` of 'undefined' or 'null'.
      at snapshot (node_modules/snap-shot/src/index.js:80:43)
      at Context.<anonymous> (src/selenium/unit/dateParseHelpers.ts:425:3)
```
