### ISSUE TITLE
Does not handle one liners

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/snap-shot#80]
Like snapshot wrapping a promise in a single line
```js
it('picks semantic commits', () => snapshot(formChangelog('1.0.0', 10)))
```
```text
 1) form changelog from commits picks semantic commits:
     Error: Could not determine test for src/form-changelog-spec.js
      line 42 column 40
      at snapshot (node_modules/snap-shot/src/index.js:117:11)
      at Context.it (src/form-changelog-spec.js:42:40)
```

**Comment by yapus** [comment]
any chance this would be fixed anytime soon?
